### PR TITLE
Fix margin in One themes

### PR DESCRIPTION
**Pull request by simurai**
The One themes will be changed so that the negative margin is not needed anymore.

### CODE REVIEW

**Comment by jerone** [comment]
[**@simurai**](https://github.com/simurai) commented on [2 mei 2015 17:44 CEST](https://github.com/suda/toolbar/pull/35#issue-72662497 "2015-05-02T15:44:26Z - Replied by Github Comment Enhancer"):
> The One themes will be changed so that the negative margin is not needed anymore.
> 
> :warning: Only merge after Atom `0.197.0` is released.

Cool. Do you have a corresponding commit from the One themes?

**Comment by simurai** [comment]
Yeah, this one: https://github.com/atom/one-dark-ui/commit/85319143ac6f6f371eba9a05bcc12c14ef44dd97

Basically moves the padding from the outer `work-space` to the inner `atom-pane`. So the toolbar isn't affected anymore.

**Comment by simurai** [comment]
Atom `0.197.0` is out and this PR can be merged.

Currently the toolbar is shifted too much to the right:

screen shot 2015-05-08 at 3 27 31 pm

**Comment by jerone** [comment]
Confirmed issue. Confirmed fix.

**Comment by suda** [comment]
Shipp'd :)

**Comment by simurai** [comment]
:+1:

**Pull request merged**
