### PR TITLE
Better support for Isotope UI theme

### LINKED ISSUE #75: Looks out-of-place with Isotope UI.
I've been told a picture's worth a thousand words, what does that make a screenshot?
screen shot 2015-06-20 at 11 44 58 pm

### PR DESCRIPTION
**Pull request by jerone**
Fixes #75 

Better support for Isotope UI themes:
* [Isotope UI theme](https://github.com/braver/isotope-ui)
* [Isotope Light UI theme](https://github.com/braver/isotope-light-ui)

Thanks to @k2b6s9j for reporting and providing the style changes.

### CODE REVIEW

**Comment by jerone** [comment]
@k2b6s9j do you have time to test this PR?

**Comment by k2b6s9j** [comment]
Yeah, I'll get on that now.

**Comment by k2b6s9j** [comment]
Isotope Dark - Top :+1: 
Isotope Dark - Bottom :+1: 
Isotope Dark - Right :+1: 
Isotope Dark - Left :unamused: 
screen shot 2015-06-21 at 10 53 41 am
screen shot 2015-06-21 at 11 00 50 am

Isotope Light - Top :+1: 
Isotope Light - Bottom :unamused: 
screen shot 2015-06-21 at 10 58 25 am
screen shot 2015-06-21 at 10 58 40 am
Isotope Light - Right :+1: 
Isotope Light - Left :unamused: 
screen shot 2015-06-21 at 10 59 50 am
screen shot 2015-06-21 at 11 00 01 am

I say it's good to merge, there are some funny corner cases but they only occur when gradients are enabled.

**Comment by k2b6s9j** [comment]
Oh and sorry it took a while.

**Comment by jerone** [comment]
I accept it for now. There will always be edge-cases. You can always open up another issue or create a PR for special issues.

**Pull request merged**
