### PR TITLE
update font-awesome icons (release 5.4.2)

### LINKED ISSUE #226: Update all Icon Sets
It'd be awesome if we could update all the icon sets to their latest versions. I know that `devicons` is missing some new icons. I will try and make a PR with updated sets!

### PR DESCRIPTION
**Pull request by unluisco**
this now use css instead of less.

this partly fix #226, but please do not close that issue since there is some iconsets that still need to be updated.

we can close #188 with this pull request.

Thanks.

### CODE REVIEW

**Comment by unluisco** [comment]
@suda can you review this? please.

Thanks.

**Comment by suda** [comment]
Thanks for the PR @unluisco! Merging and releasing now :)

**Comment by mistergraphx** [comment]
Just to inform ^^ Brand icons like Github or Chrome are broken since this update due to the separation of brand icons in v5 of Font-awesome.

**Comment by unluisco** [comment]
thanks for the clarification, @mistergraphx

**Pull request merged**
