### PR TITLE
Update Material Design Icons to v1.6.50

### PR DESCRIPTION
**Pull request by unluisco**

### CODE REVIEW

**Comment by jerone** [comment]
The test fails: https://travis-ci.org/suda/tool-bar/jobs/133624745#L229
Can you explain why it's failing.

**Comment by unluisco** [comment]
The icon 'material-ui' in the old file is /f449, but in the update file is /f357

**Comment by jerone** [comment]
Yes, please fix the specs if you with certainty can say that the code for the same icon is changed.

**Comment by unluisco** [comment]
This PR has passed the checks

**Comment by jerone** [comment]
Thanks!

**Pull request merged**
