### PR TITLE
Update ionicons icons (release v4.5.10-1)

### PR DESCRIPTION
**Pull request by ericcornelissen**
Based on #251 I decided to update the ionicons iconpack to the latest version. I'm not sure why the test was failing there, for me it was simply the case that the css classname for the icon has changed.

@suda, have you ever considered including the iconpacks as dependencies, that would make it possible to update them more quickly/easily/automatically.

### CODE REVIEW

**Comment by suda** [comment]
Thanks Eric! I believe that Atom couldn't resolve the path to the font files when being imported from the CSS when using npm dependencies, but feel free to try, maybe this isn't true anymore.

**Comment by UziTech** [comment]
Looks like this update removed a bunch of icons from the ion set.

`ion-refresh` and `ion-close` to name a few

**Comment by UziTech** [comment]
Looks like it removed all material style icons and only left ios style icons

**Comment by UziTech** [comment]
or material design icon now need to be prefaced with `md-`

**Comment by Mayccoll** [comment]
Right the `md-` fix the issue.
Thanks for the quick response

**Comment by ericcornelissen** [comment]
> or material design icon now need to be prefaced with `md-`

This seems to be what happened :wink:

**Pull request merged**
