### PR TITLE
Restore focus when clicked button. Fixed #87

### LINKED ISSUE #87: Lost focus after button clicked
See https://github.com/cakecatz/flex-toolbar/issues/45

### PR DESCRIPTION
**Pull request by cakecatz**
#87 
This PR is restore focus when clicked toolbar button.

### CODE REVIEW

**Comment by jerone** [comment]
Can you add some specs for this.

**Comment by cakecatz** [comment]
@jerone OK

**Comment by matthewwithanm** [comment]
Hi @jerone! Anything I could do to help get this merged?

**Comment by AnWeber** [comment]
hello, this merge prevents opening the command palette (command-palette:toggle). The error prone line is previouslyFocusedElement.focus(). Because of the focus on the dom element, the command-palette gets closed immediately. Any suggestions?

**Pull request merged**
