### PR TITLE
Using Github Actions

### PR DESCRIPTION
**Pull request by aminya**
- deprecates Travis, CircleCI, and Appveyor in favor of Github Actions:
Appveyor app should be removed from the repository, so it doesn't throw errors.
- Updated Eslint
- Updated Remark

See the running actions here:
https://github.com/aminya/tool-bar/actions/runs/78395908

### CODE REVIEW

**Comment by aminya** [comment]
@suda This is ready to merge. I updated the old CI and Linting stuff.

**Comment by suda** [comment]
Oh wow, that is awesome! Thanks a bunch, Amin!

**Comment by ericcornelissen** [comment]
I think the badges in the README should (have been) updated as well :sweat_smile:

**Comment by suda** [comment]
Yep, I'm doing them now :)

**Pull request merged**
